apiVersion: v1
kind: Secret
metadata:
  name: opencve
type: Opaque
stringData:
  opencve.cfg: |+
    [core]
    ; The name and the port of OpenCVE server. Change it if you launch the
    ; webserver with a different value (ie opencve webserver -b 0.0.0.0:80).
    ;server_name = 0.0.0.0:8000
    ; leaving server_name empty for it to work with k8s 
    server_name = 
    
    ; Used for securely signing the session cookie, keep it secret !
    secret_key = {{ .Values.opencve.config.secret_key }} 

    ; OpenCVE only supports PostgreSQL as database.
    {{ if .Values.postgresql.enabled }}
    database_uri = postgresql://{{ .Values.postgresql.global.postgresql.postgresqlUsername }}:{{ .Values.postgresql.global.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:5432/{{ .Values.postgresql.global.postgresql.postgresqlDatabase }}
    {{ else }}
    database_uri = {{ .Values.opencve.config.database_uri }}
    {{ end }} 

    ; see https://kombu.readthedocs.io/en/latest/userguide/connections.html#connection-urls
    {{ if and (.Values.opencve.config.celery_broker_url) (eq .Values.redis.enabled false) }}
    celery_broker_url = {{ .Values.opencve.config.celery_broker_url }}
    {{ else }}
    celery_broker_url = redis://opencve-redis-master.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379/0
    {{ end }}
    {{ if and (.Values.opencve.config.celery_result_backend) (eq .Values.redis.enabled false) }}  
    celery_result_backend = {{ .Values.opencve.config.celery_result_backend }}
    {{ else }}
    celery_result_backend = redis://opencve-redis-master.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379/1
    {{ end }}
    {{ if and (.Values.opencve.config.celery_lock_url) (eq .Values.redis.enabled false) }}
    celery_lock_url = {{ .Values.opencve.config.celery_lock_url }}
    {{ else }}
    celery_lock_url = redis://opencve-redis-master.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379/2
    {{ end }}

    ; Display the static frontpage. If False the user will be redirect to the
    ; vulnerabilitites (CVE) page.
    display_welcome = {{ .Values.opencve.config.display_welcome }}
    
    ; Display the terms of service page.
    display_terms = {{ .Values.opencve.config.display_terms }}

    ; Number of items to display in tables.
    cves_per_page = {{ .Values.opencve.display.cves_per_page }}
    vendors_per_page = {{ .Values.opencve.display.vendors_per_page }}
    products_per_page = {{ .Values.opencve.display.products_per_page }}
    cwes_per_page = {{ .Values.opencve.display.cwes_per_page }}
    reports_per_page = {{ .Values.opencve.display.reports_per_page }}
    alerts_per_page = {{ .Values.opencve.display.alerts_per_page }}
    tags_per_page = {{ .Values.opencve.display.tags_per_page }}
    activities_per_page = {{ .Values.opencve.display.activities_per_page }}

    ; Use the werkzeug middleware for reverse proxy
    ; see https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/
    use_reverse_proxy = True

    ; Display a reCAPTCHA form in register page.
    display_recaptcha = {{ .Values.opencve.recaptcha.display_recaptcha }}
    recaptcha_site_key = {{ .Values.opencve.recaptcha.recaptcha_site_key }}
    recaptcha_secret_key = {{ .Values.opencve.recaptcha.recaptcha_secret_key }}

    [api]
    ; Enable the API ratelimit
    ratelimit_enabled = {{ .Values.opencve.api.ratelimit_enabled }}

    ; Default value accross all API routes
    ; see https://flask-limiter.readthedocs.io/en/stable/#rate-limit-string-notation
    ratelimit_value = {{ .Values.opencve.api.ratelimit_value }}

    ; Ratelimit storage URI
    ; see https://limits.readthedocs.io/en/latest/storage.html
    {{ if and (.Values.opencve.config.ratelimit_storage_url) (eq Values.redis.enabled false) }}
    ratelimit_storage_url = {{ .Values.opencve.config.ratelimit_storage_url }}
    {{ else }}
    ratelimit_storage_url = redis://opencve-redis-master.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379/2
    {{ end }}

    [mail]
    ; Choices are 'smtp' or 'sendmail'
    email_adapter = {{ .Values.opencve.mail.email_adapter }}

    ; The 'From' field of the sent emails
    email_from = {{ .Values.opencve.mail.email_from }}
    
    ; Configuration to set up SMTP mails.
    smtp_server = {{ .Values.opencve.mail.smtp_server }}
    smtp_port = {{ .Values.opencve.mail.smtp_port }}
    smtp_use_tls = {{ .Values.opencve.mail.smtp_use_tls }}
    smtp_username = {{ .Values.opencve.mail.smtp_username }}
    smtp_password = {{ .Values.opencve.mail.smtp_password }}
